Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -94,3 +94,20 @@ jobs:
 #                fi
 #                docker run -d -p 5000:5000 --name app ${{ secrets.DOCKER_HUB_USERNAME }}/flask_app:latest
             run: docker run -d -p 5000:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/final_app:latest
+            
+  Check:
+      runs-on: self-hosted
+      needs: Dockerhub
+      steps:
+         - name: curl
+           id: ping
+           run: |
+               echo "::set-output name=status::$(curl -s -o response.txt -w "%{http_code}" http://20.42.116.187:5000/)"
+
+         - name: check
+           run: |
+              if [[ ${{ steps.ping.outputs.status }} != "200" ]]; then
+              echo "health check is failed"
+              exit 1
+              fi
+              echo "It's OK"
